# This file was automatically generated by SWIG
package XFree;
require Exporter;
require DynaLoader;
@ISA = qw(Exporter DynaLoader);
package XFree;
bootstrap XFree;
var_XFree_init();
package XFree;
@EXPORT = qw( );
1;

