#!/bin/sh
# Copyright (c) 2001 SuSE GmbH Nuernberg, Germany.  All rights reserved.
#
# Author: Marcus Schaefer <sax@suse.de>, 2001
# xapi script: create VNC password using the vncpasswd program
# --
#
# CVS ID:
# --------
# Status: Up-to-date
#
LC_ALL="POSIX"
VNCDIR="/root/.vnc"

if [ ! -d $VNCDIR ];then
	mkdir -p $VNCDIR && chmod 700 $VNCDIR
fi
echo $1 | vncpasswd -f > $VNCDIR/passwd
