#!/bin/sh
# Copyright (c) 2001 SuSE GmbH Nuernberg, Germany.  All rights reserved.
#
# Author: Marcus Schaefer <sax@suse.de>, 2001
# xapi script: get X11 version (ask loader)
# --
#
# CVS ID:
# --------
# Status: Up-to-date
#
export LC_ALL="POSIX"

XFree86="/usr/X11R6/bin/XFree86"
rpm -q XFree86 >/dev/null 2>&1
if [ $? = 0 ];then
	$XFree86 -version 2>&1 | grep "XFree86 Version"
else
	Xorg="/usr/X11R6/bin/Xorg"
	if [ ! -f $Xorg ];then
		Xorg=$XFree86
	fi
	$Xorg -version 2>&1 | grep "X Protocol"
fi
