# This file was automatically generated by SWIG
package PLog;
require Exporter;
require DynaLoader;
@ISA = qw(Exporter DynaLoader);
package PLog;
bootstrap PLog;
var_PLog_init();
package PLog;
@EXPORT = qw( );
1;
