#!/usr/bin/perl
# Copyright (c) 2002 SuSE GmbH Nuernberg, Germany.  All rights reserved.
#
# Author: Marcus Schaefer <sax@suse.de>, 2002
# xapi script: check if package X is installed
# --
#
# CVS ID:
# --------
# Status: Up-to-date
#
use strict;
use Env;

#----[ CheckPackage ]----------#
sub Installed {
#---------------------------------------------------
# This function checks via rpm if a package is
# installed or not.
#
	my $package = $_[0];
	my $rpm = "/bin/rpm";
	qx ($rpm -q $package 2>/dev/null >/dev/null);
	if ($? == 0) { return(1); }
	return(0);
}

#=====================================
# main...
#-------------------------------------
if (! defined $ARGV[0]) {
	print ("1\n");
	exit (1);
}
my @pacList = split (/,/,$ARGV[0]);
foreach my $package (@pacList) {
if (! Installed ($package)) {
	print ("0\n");
	exit (0);
}
}
print ("1\n");
exit (1);
