.TH xmset 1 "July 15, 2002" "Version 4.8" "Utils for X-Window"
.UC 1

.SH NAME
xmset \- set/reset X11 mouse

.SH SYNOPSIS
.B xmset
[
.I options 
]

.SH DESCRIPTION
xmset is used to apply a new mouse node/type directly to the
running X\-Server. The X11 misc extension is used to perform
this task.

.SH COMMAND LINE OPTIONS
Available command line options are the following:
.TP
-d \fIdisplay\fP
Set display to use
.TP
-s
Show current mouse configuration
.TP


-a \fIapplystring\fP
Apply new mouse configuration. The applystring is a colon
separated list containing the following elements:

1.  Real device node the mouse is connected to
.br
2.  Protocol
.br
3.  Baudrate
.br
4.  Samplerate
.br
5.  Resolution
.br
6.  Buttons
.br
7.  Emulate3Buttons (on|off)
.br
8.  Emulate3Timeout
.br
9.  ChordMiddle     (on|off)
.br
10. reopen

.TP
-D
disable the mouse pointer
.TP
-E
enable the mouse pointer after it was disabled with the 
option --disable

.SH BUGS
The currently used implementation of the X11 misc extension is
not able to apply the mouse wheel functions to the currently running
X-Server. It also is not capable of applying more than three buttons.

.SH AUTHORS
Marcus Schäfer <sax@suse.de>

.SH MAINTAINERS
The current maintainer is Marcus Schäfer. If you found a bug concering
SaX2 and/or related tools, feel free to contact Marcus <
.I sax@suse.de
>.  If you have any questions concerning support areas please contact
.I support@suse.de
.
