# This file was automatically generated by SWIG
package PLog;
require Exporter;
require DynaLoader;
@ISA = qw(Exporter DynaLoader);
package PLogc;
bootstrap PLog;
package PLog;
@EXPORT = qw( );

# ---------- BASE METHODS -------------

package PLog;

sub TIEHASH {
    my ($classname,$obj) = @_;
    return bless $obj, $classname;
}

sub CLEAR { }

sub FIRSTKEY { }

sub NEXTKEY { }

sub FETCH {
    my ($self,$field) = @_;
    my $member_func = "swig_${field}_get";
    $self->$member_func();
}

sub STORE {
    my ($self,$field,$newval) = @_;
    my $member_func = "swig_${field}_set";
    $self->$member_func($newval);
}

sub this {
    my $ptr = shift;
    return tied(%$ptr);
}


# ------- FUNCTION WRAPPERS --------

package PLog;

*PLogParse = *PLogc::PLogParse;
*PLogGetResolution = *PLogc::PLogGetResolution;
*PLogGetVideoRam = *PLogc::PLogGetVideoRam;
*PLogGetMonitorManufacturer = *PLogc::PLogGetMonitorManufacturer;
*PLogCheckDisplay = *PLogc::PLogCheckDisplay;
*PLogGetVMwareColorDepth = *PLogc::PLogGetVMwareColorDepth;
*PLogGetDisplaySize = *PLogc::PLogGetDisplaySize;

# ------- VARIABLE STUBS --------

package PLog;

1;
