#!/usr/bin/perl
# Copyright (c) 2002 SuSE GmbH Nuernberg, Germany.  All rights reserved.
#
# Author: Marcus Schaefer <sax@suse.de>, 2002
# xapi script: create 3D Environment
# --
#
# CVS ID:
# --------
# Status: Up-to-date
#
use strict;
use Env;

#---[ activate3D ]----#
sub activate3D {
#------------------------------------------------
# call the 3D script if given otherwhise prepare
# for mesasoft
#
	my $script = $_[0];
	my $path   = "/usr/X11R6/bin/";

	$script = $path.$script;
	if (-f $script) {
		qx ( $script );
	}
	return;
}

activate3D ( 
	$ARGV[0] 
);
