#!/usr/bin/perl
# Copyright (c) 2002 SuSE GmbH Nuernberg, Germany.  All rights reserved.
#
# Author: Marcus Schaefer <sax@suse.de>, 2002
# xapi script: get DDC id from sysp query call
# --
#
# CVS ID:
# --------
# Status: Up-to-date
#
use strict;
use Env;

my $sysp = "/sbin/sysp -q xstuff";
my $data = qx (
	$sysp | grep Card$ARGV[0] | grep DDC.*: | cut -f2 -d:
);
chomp ($data);
$data =~ s/[ <>]//g;
if ( $data eq "" ) {
	$data="undefined";
}

print "$data\n";
