#!/usr/bin/perl
# Copyright (c) 2002 SuSE GmbH Nuernberg, Germany.  All rights reserved.
#
# Author: Marcus Schaefer <sax@suse.de>, 2002
# xapi script: try to find the tablet port if USB
# --
#
# CVS ID:
# --------
# Status: Up-to-date
#
use strict;

my @list = ();
open (CMD,"cat /proc/bus/usb/devices*|");
while (<CMD>) {
	my $line = $_; chomp ($line);
	push (@list,$line);
}
close CMD;

for (my $i=0;$i< @list; $i++) {
	if ($list[$i] =~ /Tablet/) {
	if ($list[$i-3] =~ /Dev#= +(\d)/) {
		my $devnr = $1 + 1;
		print "/dev/input/event$devnr\n";
		exit (0);
	}
	}
}

print "/dev/input/event0\n";
exit (1);
