#!/bin/sh
# Copyright (c) 2001 SuSE GmbH Nuernberg, Germany.  All rights reserved.
#
# Author: Marcus Schaefer <sax@suse.de>, 2001
# xapi script: get X11 version (ask loader)
# --
#
# CVS ID:
# --------
# Status: Up-to-date
#
export LC_ALL="POSIX"

XFree86="/usr/X11R6/bin/XFree86"
$XFree86 -version 2>&1 | grep "XFree86 Version"
